name: Update remote test server configs

on:
  push:
    branches: [config]

jobs:
  update_config:
    runs-on: ubuntu-latest
    steps:
      - name: fetch Nginx config
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: root
          password: ${{ secrets.TEST_SERVER_SSH_KEY }}
          script: |
            cd /FedorenkaAvenue
            git pull origin config
            git checkout config
            cp /FedorenkaAvenue/remote_test_server/nginx/nginx.conf /etc/nginx/
            cp -R -f /FedorenkaAvenue/remote_test_server/nginx/conf.d /etc/nginx/
            nginx -t
            nginx -s reload
